### ISSUE TITLE
pilz_command_planner installation issues

### ISSUE THREAD

**Issue by GGU23** [PilzDE/pilz_industrial_motion#356]
Hello, I tried to follow the ros tutorial for pilz and got stuck midway with this error. I am working on a wsl under ubuntu 20.04 (ros noetic). 

### Commit
noetic-devel (latest)

### Steps to reproduce
How can the issue/bug be reproduced?
1. Follow http://wiki.ros.org/pilz_robots/Tutorials/MoveRobotWithPilzCommand_planner (and the prequisite)
2. launch `roslaunch prbt_moveit_config moveit_planning_execution.launch pipeline:=pilz_command_planner`

### Expected behavior
Rviz launched with Simple Commander Planner in the context tab

### Observed behavior
Fatal error

### Logfiles
> error as shown in the terminal:
```
RLException: while processing /opt/ros/noetic/share/prbt_moveit_config/launch/move_group.launch:
while processing /opt/ros/noetic/share/prbt_moveit_config/launch/planning_pipeline.launch.xml:
while processing /opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml'
The traceback for the exception was written to the log file
```

> logfile:
```
[roslaunch][INFO] 2022-03-28 18:53:12,999: Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2022-03-28 18:53:13,002: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2022-03-28 18:53:13,002: roslaunch starting with args ['/opt/ros/noetic/bin/roslaunch', 'prbt_moveit_config', 'moveit_planning_execution.launch', 'pipeline:=pilz_command_planner']
[roslaunch][INFO] 2022-03-28 18:53:13,002: roslaunch env is environ({'TERM': 'xterm-256color', 'TERMINATOR_UUID': 'urn:uuid:98dc4ca1-618a-4c01-a293-fb8c0ba57840', 'WSL_INTEROP': '/run/WSL/1964_interop', 'DISPLAY': ':0', 'TERMINATOR_DBUS_PATH': '/net/tenshu/Terminator2', 'USER': 'gg', 'WAYLAND_DISPLAY': 'wayland-0', 'WSL_DISTRO_NAME': 'Ubuntu20.04LTS', 'SHELL': '/usr/bin/zsh', 'PULSE_SERVER': '/mnt/wslg/PulseServer', 'TERMINATOR_DBUS_NAME': 'net.tenshu.Terminator25ef4b219e3b005583550f2b0f9f990c3', 'HOSTTYPE': 'x86_64', 'SHLVL': '1', 'LOGNAME': 'gg', '_': '/opt/ros/noetic/bin/roslaunch', 'PWD': '/home/gg/catkin_ws/src/pilz_industrial_motion', 'PATH': '/opt/ros/noetic/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Rockwell Software/RSCommon:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files (x86)/GtkSharp/2.12/bin:/mnt/c/Program Files (x86)/Java/jre1.6.0_07/bin:/mnt/c/Dart/bin:/mnt/c/Dart/bin/hapke:/mnt/c/Dart/bin/prospect:/mnt/c/Program Files/MATLAB/R2019a/bin:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/PuTTY/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Users/gg/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/gg/AppData/Local/Programs/Microsoft VS Code/bin', 'LANG': 'C.UTF-8', 'WSLENV': '', 'HOME': '/home/gg', 'COLORTERM': 'truecolor', 'XDG_RUNTIME_DIR': '/mnt/wslg/runtime-dir', 'OLDPWD': '/home/gg/catkin_ws/src', 'VTE_VERSION': '6003', 'NAME': 'PC30', 'ZSH': '/home/gg/.oh-my-zsh', 'PAGER': 'less', 'LESS': '-R', 'LSCOLORS': 'Gxfxcxdxbxegedabagacad', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'CMAKE_PREFIX_PATH': '/home/gg/catkin_ws/devel:/home/gg/ws_moveit/devel:/opt/ros/noetic', 'LD_LIBRARY_PATH': '/home/gg/catkin_ws/devel/lib:/home/gg/ws_moveit/devel/lib:/opt/ros/noetic/lib:/opt/ros/noetic/lib/x86_64-linux-gnu', 'PKG_CONFIG_PATH': '/home/gg/catkin_ws/devel/lib/pkgconfig:/home/gg/ws_moveit/devel/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/opt/ros/noetic/lib/x86_64-linux-gnu/pkgconfig', 'PYTHONPATH': '/home/gg/catkin_ws/devel/lib/python3/dist-packages:/home/gg/ws_moveit/devel/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/opt/openrobots/lib/python3.8/site-packages', 'ROS_DISTRO': 'noetic', 'ROS_ETC_DIR': '/opt/ros/noetic/etc/ros', 'ROS_PACKAGE_PATH': '/home/gg/catkin_ws/src:/home/gg/ws_moveit/src/geometric_shapes:/home/gg/ws_moveit/src/moveit/moveit:/home/gg/ws_moveit/src/moveit_msgs:/home/gg/ws_moveit/src/moveit/moveit_planners/moveit_planners:/home/gg/ws_moveit/src/moveit/moveit_plugins/moveit_plugins:/home/gg/ws_moveit/src/moveit_resources/moveit_resources:/home/gg/ws_moveit/src/moveit_resources/fanuc_description:/home/gg/ws_moveit/src/moveit_resources/fanuc_moveit_config:/home/gg/ws_moveit/src/moveit/moveit_commander:/home/gg/ws_moveit/src/moveit_resources/panda_description:/home/gg/ws_moveit/src/moveit_resources/panda_moveit_config:/home/gg/ws_moveit/src/moveit_resources/pr2_description:/home/gg/ws_moveit/src/moveit_resources/prbt_moveit_config:/home/gg/ws_moveit/src/moveit_resources/prbt_pg70_support:/home/gg/ws_moveit/src/moveit_resources/prbt_support:/home/gg/ws_moveit/src/moveit/moveit_ros/moveit_ros:/home/gg/ws_moveit/src/moveit/moveit_runtime:/home/gg/ws_moveit/src/panda_moveit_config:/home/gg/ws_moveit/src/rviz_visual_tools:/home/gg/ws_moveit/src/srdfdom:/home/gg/ws_moveit/src/moveit/moveit_core:/home/gg/ws_moveit/src/moveit/moveit_planners/chomp/chomp_motion_planner:/home/gg/ws_moveit/src/moveit/moveit_planners/chomp/chomp_optimizer_adapter:/home/gg/ws_moveit/src/moveit_resources/prbt_ikfast_manipulator_plugin:/home/gg/ws_moveit/src/moveit/moveit_ros/occupancy_map_monitor:/home/gg/ws_moveit/src/moveit/moveit_ros/planning:/home/gg/ws_moveit/src/moveit/moveit_plugins/moveit_fake_controller_manager:/home/gg/ws_moveit/src/moveit/moveit_kinematics:/home/gg/ws_moveit/src/moveit/moveit_planners/ompl:/home/gg/ws_moveit/src/moveit/moveit_ros/move_group:/home/gg/ws_moveit/src/moveit/moveit_ros/manipulation:/home/gg/ws_moveit/src/moveit/moveit_ros/perception:/home/gg/ws_moveit/src/moveit/moveit_ros/robot_interaction:/home/gg/ws_moveit/src/moveit/moveit_ros/warehouse:/home/gg/ws_moveit/src/moveit/moveit_ros/benchmarks:/home/gg/ws_moveit/src/moveit/moveit_ros/planning_interface:/home/gg/ws_moveit/src/moveit/moveit_planners/chomp/chomp_interface:/home/gg/ws_moveit/src/moveit/moveit_ros/visualization:/home/gg/ws_moveit/src/moveit/moveit_ros/moveit_servo:/home/gg/ws_moveit/src/moveit/moveit_setup_assistant:/home/gg/ws_moveit/src/moveit/moveit_plugins/moveit_simple_controller_manager:/home/gg/ws_moveit/src/moveit/moveit_plugins/moveit_ros_control_interface:/home/gg/ws_moveit/src/moveit_visual_tools:/home/gg/ws_moveit/src/moveit_tutorials:/home/gg/ws_moveit/src/moveit/moveit_planners/pilz_industrial_motion_planner_testutils:/home/gg/ws_moveit/src/moveit/moveit_planners/pilz_industrial_motion_planner:/opt/ros/noetic/share', 'ROS_PYTHON_VERSION': '3', 'ROS_VERSION': '1', 'ROS_ROOT': '/opt/ros/noetic/share/ros', 'ROS_MASTER_URI': 'http://localhost:11311', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/gg/catkin_ws/devel/share/common-lisp:/home/gg/ws_moveit/devel/share/common-lisp', 'LIBGL_ALWAYS_SOFTWARE': '1', 'ROS_LOG_FILENAME': '/home/gg/.ros/log/8e347e38-aeb7-11ec-938c-00155d30469f/roslaunch-PC30-29587.log'})
[roslaunch][INFO] 2022-03-28 18:53:13,002: starting in server mode
[roslaunch.parent][INFO] 2022-03-28 18:53:13,002: starting roslaunch parent run
[roslaunch][INFO] 2022-03-28 18:53:13,002: loading roscore config file /opt/ros/noetic/etc/ros/roscore.xml
[roslaunch][INFO] 2022-03-28 18:53:13,121: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.config][INFO] 2022-03-28 18:53:13,121: loading config file /opt/ros/noetic/share/prbt_moveit_config/launch/moveit_planning_execution.launch
[roslaunch][INFO] 2022-03-28 18:53:13,601: Added node of type [robot_state_publisher/robot_state_publisher] in namespace [/]
[roslaunch][INFO] 2022-03-28 18:53:13,601: Added node of type [joint_state_publisher/joint_state_publisher] in namespace [/]
[roslaunch][INFO] 2022-03-28 18:53:13,603: Added node of type [prbt_hardware_support/fake_speed_override_node] in namespace [/]
[roslaunch][INFO] 2022-03-28 18:53:13,603: Added node of type [rosservice/rosservice] in namespace [/]
[roslaunch][ERROR] 2022-03-28 18:53:14,017: RLException: while processing /opt/ros/noetic/share/prbt_moveit_config/launch/move_group.launch:
while processing /opt/ros/noetic/share/prbt_moveit_config/launch/planning_pipeline.launch.xml:
while processing /opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml'
[roslaunch][ERROR] 2022-03-28 18:53:14,017: The traceback for the exception was written to the log file
[roslaunch][ERROR] 2022-03-28 18:53:14,018: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 739, in _parse_launch
    root = parse(filename).getElementsByTagName('launch')
  File "/usr/lib/python3.8/xml/dom/minidom.py", line 1959, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python3.8/xml/dom/expatbuilder.py", line 910, in parse
    with open(file, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 629, in _include_tag
    launch = self._parse_launch(inc_filename, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 741, in _parse_launch
    raise XmlParseException("Invalid roslaunch XML syntax: %s"%e)
roslaunch.xmlloader.XmlParseException: Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 633, in _include_tag
    self._recurse_load(ros_config, launch.childNodes, child_ns, \
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 644, in _include_tag
    raise XmlParseException("while processing %s:\n%s"%(inc_filename, str(e)))
roslaunch.xmlloader.XmlParseException: while processing /opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 633, in _include_tag
    self._recurse_load(ros_config, launch.childNodes, child_ns, \
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 644, in _include_tag
    raise XmlParseException("while processing %s:\n%s"%(inc_filename, str(e)))
roslaunch.xmlloader.XmlParseException: while processing /opt/ros/noetic/share/prbt_moveit_config/launch/planning_pipeline.launch.xml:
while processing /opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/config.py", line 461, in load_config_default
    loader.load(f, config, argv=args, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 761, in load
    self._load_launch(launch, ros_config, is_core=core, filename=filename, argv=argv, verbose=verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 733, in _load_launch
    self._recurse_load(ros_config, launch.childNodes, self.root_context, None, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 699, in _recurse_load
    val = self._include_tag(tag, context, ros_config, default_machine, is_core, verbose)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 96, in call
    return f(*args, **kwds)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/xmlloader.py", line 644, in _include_tag
    raise XmlParseException("while processing %s:\n%s"%(inc_filename, str(e)))
roslaunch.xmlloader.XmlParseException: while processing /opt/ros/noetic/share/prbt_moveit_config/launch/move_group.launch:
while processing /opt/ros/noetic/share/prbt_moveit_config/launch/planning_pipeline.launch.xml:
while processing /opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/__init__.py", line 347, in main
    p.start()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 305, in start
    self._start_infrastructure()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 254, in _start_infrastructure
    self._load_config()
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/parent.py", line 156, in _load_config
    self.config = roslaunch.config.load_config_default(self.roslaunch_files, self.port,
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/config.py", line 463, in load_config_default
    raise RLException(e)
roslaunch.core.RLException: while processing /opt/ros/noetic/share/prbt_moveit_config/launch/move_group.launch:
while processing /opt/ros/noetic/share/prbt_moveit_config/launch/planning_pipeline.launch.xml:
while processing /opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: '/opt/ros/noetic/share/prbt_moveit_config/launch/pilz_command_planner_planning_pipeline.launch.xml'

[rospy.core][INFO] 2022-03-28 18:53:14,018: signal_shutdown [atexit]
```

### Reference to test
If there is no test that can detect the issue/bug, please create one and
reference it here.

**Comment by GGU23** [comment]
Problem solved. It was an error in the tutorial, doing a bad call to a depreciated file.

The answer to solve this issue is to change `roslaunch prbt_moveit_config moveit_planning_execution.launch pipeline:=pilz_command_planner` by `roslaunch prbt_moveit_config moveit_planning_execution.launch pipeline:=pilz_industrial_motion_planner`.
